#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InventoryManagement
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="inventory_management")]
	public partial class inventoryDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void Insertbrand(brand instance);
    partial void Updatebrand(brand instance);
    partial void Deletebrand(brand instance);
    partial void Insertcategory(category instance);
    partial void Updatecategory(category instance);
    partial void Deletecategory(category instance);
    partial void Insertcustomer(customer instance);
    partial void Updatecustomer(customer instance);
    partial void Deletecustomer(customer instance);
    partial void Insertorder(order instance);
    partial void Updateorder(order instance);
    partial void Deleteorder(order instance);
    partial void Insertorder_info(order_info instance);
    partial void Updateorder_info(order_info instance);
    partial void Deleteorder_info(order_info instance);
    partial void Insertproduct(product instance);
    partial void Updateproduct(product instance);
    partial void Deleteproduct(product instance);
    partial void Insertsale(sale instance);
    partial void Updatesale(sale instance);
    partial void Deletesale(sale instance);
    partial void Insertemployee(employee instance);
    partial void Updateemployee(employee instance);
    partial void Deleteemployee(employee instance);
    partial void Insertlogin(login instance);
    partial void Updatelogin(login instance);
    partial void Deletelogin(login instance);
    #endregion
		
		public inventoryDataContext() : 
				base(global::InventoryManagement.Properties.Settings.Default.inventory_managementConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public inventoryDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public inventoryDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public inventoryDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public inventoryDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<brand> brands
		{
			get
			{
				return this.GetTable<brand>();
			}
		}
		
		public System.Data.Linq.Table<category> categories
		{
			get
			{
				return this.GetTable<category>();
			}
		}
		
		public System.Data.Linq.Table<customer> customers
		{
			get
			{
				return this.GetTable<customer>();
			}
		}
		
		public System.Data.Linq.Table<order> orders
		{
			get
			{
				return this.GetTable<order>();
			}
		}
		
		public System.Data.Linq.Table<order_info> order_infos
		{
			get
			{
				return this.GetTable<order_info>();
			}
		}
		
		public System.Data.Linq.Table<product> products
		{
			get
			{
				return this.GetTable<product>();
			}
		}
		
		public System.Data.Linq.Table<sale> sales
		{
			get
			{
				return this.GetTable<sale>();
			}
		}
		
		public System.Data.Linq.Table<employee> employees
		{
			get
			{
				return this.GetTable<employee>();
			}
		}
		
		public System.Data.Linq.Table<login> logins
		{
			get
			{
				return this.GetTable<login>();
			}
		}
		
		public System.Data.Linq.Table<sale_info> sale_infos
		{
			get
			{
				return this.GetTable<sale_info>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.brands")]
	public partial class brand : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _brand_id;
		
		private string _brand_title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onbrand_idChanging(int value);
    partial void Onbrand_idChanged();
    partial void Onbrand_titleChanging(string value);
    partial void Onbrand_titleChanged();
    #endregion
		
		public brand()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int brand_id
		{
			get
			{
				return this._brand_id;
			}
			set
			{
				if ((this._brand_id != value))
				{
					this.Onbrand_idChanging(value);
					this.SendPropertyChanging();
					this._brand_id = value;
					this.SendPropertyChanged("brand_id");
					this.Onbrand_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_brand_title", DbType="NChar(10)")]
		public string brand_title
		{
			get
			{
				return this._brand_title;
			}
			set
			{
				if ((this._brand_title != value))
				{
					this.Onbrand_titleChanging(value);
					this.SendPropertyChanging();
					this._brand_title = value;
					this.SendPropertyChanged("brand_title");
					this.Onbrand_titleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.categories")]
	public partial class category : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cat_id;
		
		private string _cat_title;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncat_idChanging(int value);
    partial void Oncat_idChanged();
    partial void Oncat_titleChanging(string value);
    partial void Oncat_titleChanged();
    #endregion
		
		public category()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cat_id
		{
			get
			{
				return this._cat_id;
			}
			set
			{
				if ((this._cat_id != value))
				{
					this.Oncat_idChanging(value);
					this.SendPropertyChanging();
					this._cat_id = value;
					this.SendPropertyChanged("cat_id");
					this.Oncat_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cat_title", DbType="VarChar(50)")]
		public string cat_title
		{
			get
			{
				return this._cat_title;
			}
			set
			{
				if ((this._cat_title != value))
				{
					this.Oncat_titleChanging(value);
					this.SendPropertyChanging();
					this._cat_title = value;
					this.SendPropertyChanged("cat_title");
					this.Oncat_titleChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.customers")]
	public partial class customer : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _cust_id;
		
		private string _cust_name;
		
		private string _cust_phone;
		
		private string _cust_email;
		
		private string _email_address;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Oncust_idChanging(int value);
    partial void Oncust_idChanged();
    partial void Oncust_nameChanging(string value);
    partial void Oncust_nameChanged();
    partial void Oncust_phoneChanging(string value);
    partial void Oncust_phoneChanged();
    partial void Oncust_emailChanging(string value);
    partial void Oncust_emailChanged();
    partial void Onemail_addressChanging(string value);
    partial void Onemail_addressChanged();
    #endregion
		
		public customer()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int cust_id
		{
			get
			{
				return this._cust_id;
			}
			set
			{
				if ((this._cust_id != value))
				{
					this.Oncust_idChanging(value);
					this.SendPropertyChanging();
					this._cust_id = value;
					this.SendPropertyChanged("cust_id");
					this.Oncust_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_name", DbType="VarChar(50)")]
		public string cust_name
		{
			get
			{
				return this._cust_name;
			}
			set
			{
				if ((this._cust_name != value))
				{
					this.Oncust_nameChanging(value);
					this.SendPropertyChanging();
					this._cust_name = value;
					this.SendPropertyChanged("cust_name");
					this.Oncust_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_phone", DbType="VarChar(50)")]
		public string cust_phone
		{
			get
			{
				return this._cust_phone;
			}
			set
			{
				if ((this._cust_phone != value))
				{
					this.Oncust_phoneChanging(value);
					this.SendPropertyChanging();
					this._cust_phone = value;
					this.SendPropertyChanged("cust_phone");
					this.Oncust_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_email", DbType="VarChar(50)")]
		public string cust_email
		{
			get
			{
				return this._cust_email;
			}
			set
			{
				if ((this._cust_email != value))
				{
					this.Oncust_emailChanging(value);
					this.SendPropertyChanging();
					this._cust_email = value;
					this.SendPropertyChanged("cust_email");
					this.Oncust_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_email_address", DbType="VarChar(MAX)")]
		public string email_address
		{
			get
			{
				return this._email_address;
			}
			set
			{
				if ((this._email_address != value))
				{
					this.Onemail_addressChanging(value);
					this.SendPropertyChanging();
					this._email_address = value;
					this.SendPropertyChanged("email_address");
					this.Onemail_addressChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.[order]")]
	public partial class order : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _order_id;
		
		private System.Nullable<System.DateTime> _order_date;
		
		private System.Nullable<System.DateTime> _order_shipment;
		
		private string _vendor_name;
		
		private System.Nullable<decimal> _total_bill;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void Onorder_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onorder_dateChanged();
    partial void Onorder_shipmentChanging(System.Nullable<System.DateTime> value);
    partial void Onorder_shipmentChanged();
    partial void Onvendor_nameChanging(string value);
    partial void Onvendor_nameChanged();
    partial void Ontotal_billChanging(System.Nullable<decimal> value);
    partial void Ontotal_billChanged();
    #endregion
		
		public order()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_date", DbType="Date")]
		public System.Nullable<System.DateTime> order_date
		{
			get
			{
				return this._order_date;
			}
			set
			{
				if ((this._order_date != value))
				{
					this.Onorder_dateChanging(value);
					this.SendPropertyChanging();
					this._order_date = value;
					this.SendPropertyChanged("order_date");
					this.Onorder_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_shipment", DbType="Date")]
		public System.Nullable<System.DateTime> order_shipment
		{
			get
			{
				return this._order_shipment;
			}
			set
			{
				if ((this._order_shipment != value))
				{
					this.Onorder_shipmentChanging(value);
					this.SendPropertyChanging();
					this._order_shipment = value;
					this.SendPropertyChanged("order_shipment");
					this.Onorder_shipmentChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_vendor_name", DbType="VarChar(50)")]
		public string vendor_name
		{
			get
			{
				return this._vendor_name;
			}
			set
			{
				if ((this._vendor_name != value))
				{
					this.Onvendor_nameChanging(value);
					this.SendPropertyChanging();
					this._vendor_name = value;
					this.SendPropertyChanged("vendor_name");
					this.Onvendor_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_bill", DbType="Money")]
		public System.Nullable<decimal> total_bill
		{
			get
			{
				return this._total_bill;
			}
			set
			{
				if ((this._total_bill != value))
				{
					this.Ontotal_billChanging(value);
					this.SendPropertyChanging();
					this._total_bill = value;
					this.SendPropertyChanged("total_bill");
					this.Ontotal_billChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.order_info")]
	public partial class order_info : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _order_id;
		
		private System.Nullable<int> _pro_id;
		
		private string _pro_title;
		
		private System.Nullable<decimal> _pro_price;
		
		private System.Nullable<int> _pro_quantity;
		
		private System.Nullable<decimal> _total;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onorder_idChanging(int value);
    partial void Onorder_idChanged();
    partial void Onpro_idChanging(System.Nullable<int> value);
    partial void Onpro_idChanged();
    partial void Onpro_titleChanging(string value);
    partial void Onpro_titleChanged();
    partial void Onpro_priceChanging(System.Nullable<decimal> value);
    partial void Onpro_priceChanged();
    partial void Onpro_quantityChanging(System.Nullable<int> value);
    partial void Onpro_quantityChanged();
    partial void OntotalChanging(System.Nullable<decimal> value);
    partial void OntotalChanged();
    #endregion
		
		public order_info()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_order_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int order_id
		{
			get
			{
				return this._order_id;
			}
			set
			{
				if ((this._order_id != value))
				{
					this.Onorder_idChanging(value);
					this.SendPropertyChanging();
					this._order_id = value;
					this.SendPropertyChanged("order_id");
					this.Onorder_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int")]
		public System.Nullable<int> pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_title", DbType="VarChar(50)")]
		public string pro_title
		{
			get
			{
				return this._pro_title;
			}
			set
			{
				if ((this._pro_title != value))
				{
					this.Onpro_titleChanging(value);
					this.SendPropertyChanging();
					this._pro_title = value;
					this.SendPropertyChanged("pro_title");
					this.Onpro_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_price", DbType="Money")]
		public System.Nullable<decimal> pro_price
		{
			get
			{
				return this._pro_price;
			}
			set
			{
				if ((this._pro_price != value))
				{
					this.Onpro_priceChanging(value);
					this.SendPropertyChanging();
					this._pro_price = value;
					this.SendPropertyChanged("pro_price");
					this.Onpro_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_quantity", DbType="Int")]
		public System.Nullable<int> pro_quantity
		{
			get
			{
				return this._pro_quantity;
			}
			set
			{
				if ((this._pro_quantity != value))
				{
					this.Onpro_quantityChanging(value);
					this.SendPropertyChanging();
					this._pro_quantity = value;
					this.SendPropertyChanged("pro_quantity");
					this.Onpro_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Money")]
		public System.Nullable<decimal> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.products")]
	public partial class product : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _pro_id;
		
		private string _Pro_cat;
		
		private string _pro_brand;
		
		private string _pro_title;
		
		private System.Nullable<decimal> _pro_price;
		
		private System.Nullable<int> _pro_quantity;
		
		private System.Nullable<int> _pro_warranty;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onpro_idChanging(int value);
    partial void Onpro_idChanged();
    partial void OnPro_catChanging(string value);
    partial void OnPro_catChanged();
    partial void Onpro_brandChanging(string value);
    partial void Onpro_brandChanged();
    partial void Onpro_titleChanging(string value);
    partial void Onpro_titleChanged();
    partial void Onpro_priceChanging(System.Nullable<decimal> value);
    partial void Onpro_priceChanged();
    partial void Onpro_quantityChanging(System.Nullable<int> value);
    partial void Onpro_quantityChanged();
    partial void Onpro_warrantyChanging(System.Nullable<int> value);
    partial void Onpro_warrantyChanged();
    #endregion
		
		public product()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this.Onpro_idChanging(value);
					this.SendPropertyChanging();
					this._pro_id = value;
					this.SendPropertyChanged("pro_id");
					this.Onpro_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pro_cat", DbType="VarChar(50)")]
		public string Pro_cat
		{
			get
			{
				return this._Pro_cat;
			}
			set
			{
				if ((this._Pro_cat != value))
				{
					this.OnPro_catChanging(value);
					this.SendPropertyChanging();
					this._Pro_cat = value;
					this.SendPropertyChanged("Pro_cat");
					this.OnPro_catChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_brand", DbType="VarChar(50)")]
		public string pro_brand
		{
			get
			{
				return this._pro_brand;
			}
			set
			{
				if ((this._pro_brand != value))
				{
					this.Onpro_brandChanging(value);
					this.SendPropertyChanging();
					this._pro_brand = value;
					this.SendPropertyChanged("pro_brand");
					this.Onpro_brandChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_title", DbType="VarChar(50)")]
		public string pro_title
		{
			get
			{
				return this._pro_title;
			}
			set
			{
				if ((this._pro_title != value))
				{
					this.Onpro_titleChanging(value);
					this.SendPropertyChanging();
					this._pro_title = value;
					this.SendPropertyChanged("pro_title");
					this.Onpro_titleChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_price", DbType="Money")]
		public System.Nullable<decimal> pro_price
		{
			get
			{
				return this._pro_price;
			}
			set
			{
				if ((this._pro_price != value))
				{
					this.Onpro_priceChanging(value);
					this.SendPropertyChanging();
					this._pro_price = value;
					this.SendPropertyChanged("pro_price");
					this.Onpro_priceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_quantity", DbType="Int")]
		public System.Nullable<int> pro_quantity
		{
			get
			{
				return this._pro_quantity;
			}
			set
			{
				if ((this._pro_quantity != value))
				{
					this.Onpro_quantityChanging(value);
					this.SendPropertyChanging();
					this._pro_quantity = value;
					this.SendPropertyChanged("pro_quantity");
					this.Onpro_quantityChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_warranty", DbType="Int")]
		public System.Nullable<int> pro_warranty
		{
			get
			{
				return this._pro_warranty;
			}
			set
			{
				if ((this._pro_warranty != value))
				{
					this.Onpro_warrantyChanging(value);
					this.SendPropertyChanging();
					this._pro_warranty = value;
					this.SendPropertyChanged("pro_warranty");
					this.Onpro_warrantyChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sales")]
	public partial class sale : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _sale_id;
		
		private System.Nullable<int> _user_id;
		
		private System.Nullable<System.DateTime> _sale_date;
		
		private string _cust_phone;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsale_idChanging(int value);
    partial void Onsale_idChanged();
    partial void Onuser_idChanging(System.Nullable<int> value);
    partial void Onuser_idChanged();
    partial void Onsale_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onsale_dateChanged();
    partial void Oncust_phoneChanging(string value);
    partial void Oncust_phoneChanged();
    #endregion
		
		public sale()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sale_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int sale_id
		{
			get
			{
				return this._sale_id;
			}
			set
			{
				if ((this._sale_id != value))
				{
					this.Onsale_idChanging(value);
					this.SendPropertyChanging();
					this._sale_id = value;
					this.SendPropertyChanged("sale_id");
					this.Onsale_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int")]
		public System.Nullable<int> user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_sale_date", DbType="Date")]
		public System.Nullable<System.DateTime> sale_date
		{
			get
			{
				return this._sale_date;
			}
			set
			{
				if ((this._sale_date != value))
				{
					this.Onsale_dateChanging(value);
					this.SendPropertyChanging();
					this._sale_date = value;
					this.SendPropertyChanged("sale_date");
					this.Onsale_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_cust_phone", DbType="VarChar(50)")]
		public string cust_phone
		{
			get
			{
				return this._cust_phone;
			}
			set
			{
				if ((this._cust_phone != value))
				{
					this.Oncust_phoneChanging(value);
					this.SendPropertyChanging();
					this._cust_phone = value;
					this.SendPropertyChanged("cust_phone");
					this.Oncust_phoneChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.employees")]
	public partial class employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _emp_id;
		
		private string _emp_name;
		
		private string _emp_gender;
		
		private System.Nullable<System.DateTime> _emp_dob;
		
		private string _emp_email;
		
		private string _emp_phone;
		
		private string _emp_nid;
		
		private string _emp_address;
		
		private System.Nullable<System.DateTime> _emp_join_date;
		
		private System.Nullable<decimal> _emp_sal;
		
		private string _emp_rank;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onemp_idChanging(int value);
    partial void Onemp_idChanged();
    partial void Onemp_nameChanging(string value);
    partial void Onemp_nameChanged();
    partial void Onemp_genderChanging(string value);
    partial void Onemp_genderChanged();
    partial void Onemp_dobChanging(System.Nullable<System.DateTime> value);
    partial void Onemp_dobChanged();
    partial void Onemp_emailChanging(string value);
    partial void Onemp_emailChanged();
    partial void Onemp_phoneChanging(string value);
    partial void Onemp_phoneChanged();
    partial void Onemp_nidChanging(string value);
    partial void Onemp_nidChanged();
    partial void Onemp_addressChanging(string value);
    partial void Onemp_addressChanged();
    partial void Onemp_join_dateChanging(System.Nullable<System.DateTime> value);
    partial void Onemp_join_dateChanged();
    partial void Onemp_salChanging(System.Nullable<decimal> value);
    partial void Onemp_salChanged();
    partial void Onemp_rankChanging(string value);
    partial void Onemp_rankChanged();
    #endregion
		
		public employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int emp_id
		{
			get
			{
				return this._emp_id;
			}
			set
			{
				if ((this._emp_id != value))
				{
					this.Onemp_idChanging(value);
					this.SendPropertyChanging();
					this._emp_id = value;
					this.SendPropertyChanged("emp_id");
					this.Onemp_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_name", DbType="VarChar(50)")]
		public string emp_name
		{
			get
			{
				return this._emp_name;
			}
			set
			{
				if ((this._emp_name != value))
				{
					this.Onemp_nameChanging(value);
					this.SendPropertyChanging();
					this._emp_name = value;
					this.SendPropertyChanged("emp_name");
					this.Onemp_nameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_gender", DbType="VarChar(50)")]
		public string emp_gender
		{
			get
			{
				return this._emp_gender;
			}
			set
			{
				if ((this._emp_gender != value))
				{
					this.Onemp_genderChanging(value);
					this.SendPropertyChanging();
					this._emp_gender = value;
					this.SendPropertyChanged("emp_gender");
					this.Onemp_genderChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_dob", DbType="Date")]
		public System.Nullable<System.DateTime> emp_dob
		{
			get
			{
				return this._emp_dob;
			}
			set
			{
				if ((this._emp_dob != value))
				{
					this.Onemp_dobChanging(value);
					this.SendPropertyChanging();
					this._emp_dob = value;
					this.SendPropertyChanged("emp_dob");
					this.Onemp_dobChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_email", DbType="VarChar(50)")]
		public string emp_email
		{
			get
			{
				return this._emp_email;
			}
			set
			{
				if ((this._emp_email != value))
				{
					this.Onemp_emailChanging(value);
					this.SendPropertyChanging();
					this._emp_email = value;
					this.SendPropertyChanged("emp_email");
					this.Onemp_emailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_phone", DbType="VarChar(50)")]
		public string emp_phone
		{
			get
			{
				return this._emp_phone;
			}
			set
			{
				if ((this._emp_phone != value))
				{
					this.Onemp_phoneChanging(value);
					this.SendPropertyChanging();
					this._emp_phone = value;
					this.SendPropertyChanged("emp_phone");
					this.Onemp_phoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_nid", DbType="VarChar(50)")]
		public string emp_nid
		{
			get
			{
				return this._emp_nid;
			}
			set
			{
				if ((this._emp_nid != value))
				{
					this.Onemp_nidChanging(value);
					this.SendPropertyChanging();
					this._emp_nid = value;
					this.SendPropertyChanged("emp_nid");
					this.Onemp_nidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_address", DbType="NVarChar(MAX)")]
		public string emp_address
		{
			get
			{
				return this._emp_address;
			}
			set
			{
				if ((this._emp_address != value))
				{
					this.Onemp_addressChanging(value);
					this.SendPropertyChanging();
					this._emp_address = value;
					this.SendPropertyChanged("emp_address");
					this.Onemp_addressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_join_date", DbType="Date")]
		public System.Nullable<System.DateTime> emp_join_date
		{
			get
			{
				return this._emp_join_date;
			}
			set
			{
				if ((this._emp_join_date != value))
				{
					this.Onemp_join_dateChanging(value);
					this.SendPropertyChanging();
					this._emp_join_date = value;
					this.SendPropertyChanged("emp_join_date");
					this.Onemp_join_dateChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_sal", DbType="Money")]
		public System.Nullable<decimal> emp_sal
		{
			get
			{
				return this._emp_sal;
			}
			set
			{
				if ((this._emp_sal != value))
				{
					this.Onemp_salChanging(value);
					this.SendPropertyChanging();
					this._emp_sal = value;
					this.SendPropertyChanged("emp_sal");
					this.Onemp_salChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_emp_rank", DbType="VarChar(50)")]
		public string emp_rank
		{
			get
			{
				return this._emp_rank;
			}
			set
			{
				if ((this._emp_rank != value))
				{
					this.Onemp_rankChanging(value);
					this.SendPropertyChanging();
					this._emp_rank = value;
					this.SendPropertyChanged("emp_rank");
					this.Onemp_rankChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.login")]
	public partial class login : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _user_id;
		
		private string _user_type;
		
		private string _user_pass;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onuser_idChanging(int value);
    partial void Onuser_idChanged();
    partial void Onuser_typeChanging(string value);
    partial void Onuser_typeChanged();
    partial void Onuser_passChanging(string value);
    partial void Onuser_passChanged();
    #endregion
		
		public login()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int user_id
		{
			get
			{
				return this._user_id;
			}
			set
			{
				if ((this._user_id != value))
				{
					this.Onuser_idChanging(value);
					this.SendPropertyChanging();
					this._user_id = value;
					this.SendPropertyChanged("user_id");
					this.Onuser_idChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_type", DbType="VarChar(50)")]
		public string user_type
		{
			get
			{
				return this._user_type;
			}
			set
			{
				if ((this._user_type != value))
				{
					this.Onuser_typeChanging(value);
					this.SendPropertyChanging();
					this._user_type = value;
					this.SendPropertyChanged("user_type");
					this.Onuser_typeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_user_pass", DbType="VarChar(50)")]
		public string user_pass
		{
			get
			{
				return this._user_pass;
			}
			set
			{
				if ((this._user_pass != value))
				{
					this.Onuser_passChanging(value);
					this.SendPropertyChanging();
					this._user_pass = value;
					this.SendPropertyChanged("user_pass");
					this.Onuser_passChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.sale_info")]
	public partial class sale_info
	{
		
		private System.Nullable<int> _pro_id;
		
		private string _pro_title;
		
		private System.Nullable<int> _pro_warranty;
		
		private System.Nullable<int> _pro_quantity;
		
		private System.Nullable<decimal> _total_price;
		
		public sale_info()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_id", DbType="Int")]
		public System.Nullable<int> pro_id
		{
			get
			{
				return this._pro_id;
			}
			set
			{
				if ((this._pro_id != value))
				{
					this._pro_id = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_title", DbType="VarChar(50)")]
		public string pro_title
		{
			get
			{
				return this._pro_title;
			}
			set
			{
				if ((this._pro_title != value))
				{
					this._pro_title = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_warranty", DbType="Int")]
		public System.Nullable<int> pro_warranty
		{
			get
			{
				return this._pro_warranty;
			}
			set
			{
				if ((this._pro_warranty != value))
				{
					this._pro_warranty = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_pro_quantity", DbType="Int")]
		public System.Nullable<int> pro_quantity
		{
			get
			{
				return this._pro_quantity;
			}
			set
			{
				if ((this._pro_quantity != value))
				{
					this._pro_quantity = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total_price", DbType="Money")]
		public System.Nullable<decimal> total_price
		{
			get
			{
				return this._total_price;
			}
			set
			{
				if ((this._total_price != value))
				{
					this._total_price = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
